"use client";

import { Clock3, Copy, MousePointer2, Trash2, UserRound } from "lucide-react";
import { useI18n } from "@/i18n/provider";
import type { TranslationKey } from "@/i18n/types";
import { useEditorStore } from "@/store/editor-store";
import { useToast } from "@/components/ui/toast";

const typeLabel = { start: "node.start", task: "node.task", approval: "node.approval", condition: "node.condition", end: "node.end" } satisfies Record<string, TranslationKey>;
export function PropertiesPanel() {
  const { t } = useI18n(); const { notify } = useToast(); const selectedId = useEditorStore((state) => state.selectedNodeId); const node = useEditorStore((state) => state.nodes.find((item) => item.id === selectedId)); const updateNode = useEditorStore((state) => state.updateNode); const duplicate = useEditorStore((state) => state.duplicateSelected); const remove = useEditorStore((state) => state.deleteSelected);
  if (!node) return <aside className="properties z-10 border-l border-line bg-surface p-5"><div className="section-label">{t("properties.title")}</div><div className="flex h-[calc(100%-32px)] flex-col items-center justify-center px-3 text-center"><span className="mb-4 flex h-12 w-12 items-center justify-center rounded-xl border border-line bg-canvas text-muted"><MousePointer2 size={20} /></span><h2 className="text-sm font-bold">{t("properties.emptyTitle")}</h2><p className="mt-1.5 max-w-[220px] text-[10px] leading-5 text-muted">{t("properties.emptyText")}</p></div></aside>;
  const fieldClass = "mt-1.5 w-full rounded-[9px] border border-line bg-canvas px-3 py-2.5 text-xs text-ink transition placeholder:text-muted focus:border-brand focus:bg-surface";
  return <aside className="properties z-10 overflow-y-auto border-l border-line bg-surface p-5"><div className="flex items-center justify-between"><div className="section-label">{t("properties.title")}</div><span className="rounded-md border border-line bg-canvas px-2 py-1 text-[9px] font-bold text-muted">{t(typeLabel[node.type])}</span></div><div className="mt-5 space-y-4"><label className="field-label">{t("properties.name")}<input className={fieldClass} value={node.data.label} onChange={(event) => updateNode(node.id, { label: event.target.value })} /></label><label className="field-label">{t("properties.description")}<textarea rows={4} className={`${fieldClass} resize-none leading-5`} value={node.data.description} onChange={(event) => updateNode(node.id, { description: event.target.value })} placeholder={t("properties.descriptionPlaceholder")} /></label><label className="field-label"><span className="flex items-center gap-1.5"><UserRound size={13} />{t("properties.assignee")}</span><input className={fieldClass} value={node.data.assignee} onChange={(event) => updateNode(node.id, { assignee: event.target.value })} placeholder={t("properties.assigneePlaceholder")} /></label><label className="field-label"><span className="flex items-center gap-1.5"><Clock3 size={13} />{t("properties.duration")}</span><input className={fieldClass} value={node.data.duration} onChange={(event) => updateNode(node.id, { duration: event.target.value })} placeholder={t("properties.durationPlaceholder")} /></label></div><div className="mt-6 border-t border-line pt-4"><div className="flex gap-2"><button onClick={() => { duplicate(); notify(t("toast.duplicated")); }} className="secondary-button flex-1 justify-center" aria-label={t("properties.duplicate")}><Copy size={13} />{t("properties.duplicate")}</button><button onClick={() => { remove(); notify(t("toast.deleted")); }} className="danger-button flex-1 justify-center" aria-label={t("properties.delete")}><Trash2 size={13} />{t("properties.delete")}</button></div><p className="mt-3 text-center text-[9px] text-muted">{t("properties.shortcuts")}</p></div></aside>;
}
