"use client";

import { CircleHelp, Cloud, FolderCog, History, Info, LogIn, LogOut, Moon, Play, Redo2, Sun, Undo2 } from "lucide-react";
import { useAccount } from "@/components/account/account-provider";
import { useI18n } from "@/i18n/provider";
import type { Locale, TranslationKey } from "@/i18n/types";
import { useEditorStore } from "@/store/editor-store";

type TopBarProps = { onGuide: () => void; onAbout: () => void; onRun: () => void; onAuth: () => void; onProcesses: () => void; onVersions: () => void; onTools: () => void };

export function TopBar({ onGuide, onAbout, onRun, onAuth, onProcesses, onVersions, onTools }: TopBarProps) {
  const { t, locale, setLocale } = useI18n(); const account = useAccount();
  const workflowName = useEditorStore((state) => state.workflowName); const setWorkflowName = useEditorStore((state) => state.setWorkflowName); const theme = useEditorStore((state) => state.theme); const setTheme = useEditorStore((state) => state.setTheme); const saveStatus = useEditorStore((state) => state.saveStatus); const currentProcessId = useEditorStore((state) => state.currentProcessId); const undo = useEditorStore((state) => state.undo); const redo = useEditorStore((state) => state.redo); const canUndo = useEditorStore((state) => state.past.length > 0); const canRedo = useEditorStore((state) => state.future.length > 0);
  const statusKey = ({ saving: "status.saving", saved: "status.saved", error: "status.error", offline: "status.offline" } as const)[saveStatus] satisfies TranslationKey;
  const statusDot = saveStatus === "saving" ? "animate-pulse bg-amber-400" : saveStatus === "error" ? "bg-rose-500" : saveStatus === "offline" ? "bg-orange-500" : "bg-emerald-500";
  const changeLocale = (next: Locale) => { if (next !== locale) setLocale(next); };
  return <header className="top-bar flex h-[68px] shrink-0 items-center gap-4 border-b border-line bg-surface px-4 lg:px-5">
    <div className="brand-area flex min-w-[214px] items-center gap-3"><span className="brand-mark"><i /><i /><i /></span><div><div className="text-[15px] font-extrabold tracking-[-0.035em]">ProcessCanvas</div><div className="mt-0.5 text-[9px] font-semibold uppercase tracking-[0.13em] text-muted">{t("app.tagline")}</div></div></div><div className="h-8 w-px bg-line" />
    <div className="min-w-0 flex-1"><input aria-label={t("top.workflowName")} value={workflowName} onChange={(event) => setWorkflowName(event.target.value)} className="w-full max-w-[380px] rounded-md border border-transparent bg-transparent px-2 py-1 text-sm font-bold tracking-[-0.01em] text-ink transition hover:border-line focus:border-brand focus:bg-canvas" /><div data-tutorial-target="save-status" className="ml-2 mt-0.5 flex items-center gap-1.5 text-[9px] font-medium text-muted"><span className={`h-1.5 w-1.5 rounded-full ${statusDot}`} />{t(statusKey)}<span className="hidden xl:inline">· {t(currentProcessId ? "status.server" : "status.local")}</span></div></div>
    <div className="flex items-center gap-1"><button data-tutorial-target="undo" onClick={() => undo()} disabled={!canUndo} aria-label={t("top.undo")} title={`${t("top.undo")} · Ctrl/⌘ Z`} className="icon-button"><Undo2 size={17} /></button><button data-tutorial-target="redo" onClick={() => redo()} disabled={!canRedo} aria-label={t("top.redo")} title={`${t("top.redo")} · Ctrl/⌘ Shift Z`} className="icon-button"><Redo2 size={17} /></button><span className="mx-1 h-5 w-px bg-line" /><button onClick={onGuide} aria-label={t("top.guide")} title={t("top.guide")} className="icon-button"><CircleHelp size={17} /></button><button onClick={onTools} aria-label={t("top.tools")} title={t("top.tools")} className="icon-button"><FolderCog size={17} /></button><button onClick={onAbout} aria-label={t("top.about")} title={t("top.about")} className="icon-button"><Info size={17} /></button>
      {account.session && <><button onClick={onVersions} disabled={!currentProcessId} aria-label={t("top.versions")} title={t("top.versions")} className="icon-button"><History size={16} /></button><button onClick={onProcesses} aria-label={t("top.myProcesses")} title={t("top.myProcesses")} className="secondary-button max-w-[132px]"><Cloud size={13} /><span className="truncate">{account.session.user.name}</span></button><button onClick={() => account.logout()} aria-label={t("top.logout")} title={t("top.logout")} className="icon-button"><LogOut size={16} /></button></>}
      {!account.loading && !account.session && <button onClick={onAuth} className="secondary-button"><LogIn size={13} />{t("top.signIn")}</button>}
      <div className="language-switch ml-1 flex rounded-lg border border-line bg-canvas p-0.5" aria-label={t("top.language")}>{(["ru", "en"] as Locale[]).map((item) => <button key={item} onClick={() => changeLocale(item)} className={`rounded-md px-2 py-1.5 text-[9px] font-bold uppercase transition ${locale === item ? "bg-surface text-ink shadow-sm" : "text-muted hover:text-ink"}`} aria-pressed={locale === item}>{item}</button>)}</div><button onClick={() => setTheme(theme === "dark" ? "light" : "dark")} aria-label={theme === "dark" ? t("top.themeLight") : t("top.themeDark")} title={theme === "dark" ? t("top.themeLight") : t("top.themeDark")} className="icon-button ml-1">{theme === "dark" ? <Sun size={17} /> : <Moon size={17} />}</button><button onClick={onRun} title={t("top.run")} className="run-button ml-2 opacity-100" aria-label={t("top.run")}><Play size={13} fill="currentColor" />{t("top.run")}</button>
    </div>
  </header>;
}
