"use client";

import { Eye, EyeOff, LoaderCircle } from "lucide-react";
import { useState, type FormEvent } from "react";
import { Modal } from "@/components/ui/modal";
import { useI18n } from "@/i18n/provider";
import type { TranslationKey } from "@/i18n/types";
import { ApiClientError } from "@/lib/api-client";
import { useAccount } from "./account-provider";

const errorKeys: Record<string, TranslationKey> = { invalid_credentials: "auth.error.invalid_credentials", email_exists: "auth.error.email_exists", validation_error: "auth.error.validation_error", network_error: "auth.error.network_error", timeout: "auth.error.network_error" };
export function AuthModal({ onClose }: { onClose: () => void }) {
  const { t } = useI18n(); const account = useAccount(); const [mode, setMode] = useState<"login" | "register">("login"); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [show, setShow] = useState(false); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState<TranslationKey | null>(null);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSubmitting(true); setError(null); try { if (mode === "login") await account.login(email, password); else await account.register(name, email, password); onClose(); } catch (requestError) { const code = requestError instanceof ApiClientError ? requestError.code : "default"; setError(errorKeys[code] ?? "auth.error.default"); } finally { setSubmitting(false); } };
  const field = "mt-1.5 w-full rounded-[10px] border border-line bg-canvas px-3 py-2.5 text-xs text-ink focus:border-brand";
  return <Modal title={t("auth.title")} onClose={onClose}><form className="p-5" onSubmit={submit}><div className="mb-5 grid grid-cols-2 rounded-xl bg-canvas p-1"><button type="button" className={`rounded-lg py-2 text-[10px] font-bold ${mode === "login" ? "bg-surface shadow-sm" : "text-muted"}`} onClick={() => setMode("login")}>{t("auth.login")}</button><button type="button" className={`rounded-lg py-2 text-[10px] font-bold ${mode === "register" ? "bg-surface shadow-sm" : "text-muted"}`} onClick={() => setMode("register")}>{t("auth.register")}</button></div><div className="grid gap-4">{mode === "register" && <label className="field-label">{t("auth.name")}<input required minLength={2} maxLength={80} autoComplete="name" className={field} value={name} onChange={(event) => setName(event.target.value)} /></label>}<label className="field-label">{t("auth.email")}<input required type="email" autoComplete="email" className={field} value={email} onChange={(event) => setEmail(event.target.value)} /></label><label className="field-label">{t("auth.password")}<span className="relative mt-1.5 block"><input required minLength={8} maxLength={128} type={show ? "text" : "password"} autoComplete={mode === "login" ? "current-password" : "new-password"} className={`${field} mt-0 pr-10`} value={password} onChange={(event) => setPassword(event.target.value)} /><button type="button" className="icon-button absolute right-1 top-1" onClick={() => setShow((value) => !value)} aria-label={show ? t("auth.hidePassword") : t("auth.showPassword")}>{show ? <EyeOff size={15} /> : <Eye size={15} />}</button></span></label></div>{error && <p className="mt-4 rounded-lg bg-rose-50 px-3 py-2 text-[10px] font-semibold text-rose-700 dark:bg-rose-950 dark:text-rose-200">{t(error)}</p>}<button className="primary-button mt-5 w-full py-2.5" disabled={submitting}>{submitting && <LoaderCircle size={14} className="animate-spin" />}{t(mode === "login" ? "auth.submitLogin" : "auth.submitRegister")}</button><button type="button" className="mt-3 w-full text-center text-[10px] font-bold text-brand" onClick={() => setMode(mode === "login" ? "register" : "login")}>{t(mode === "login" ? "auth.switchRegister" : "auth.switchLogin")}</button></form></Modal>;
}
